const About = () =>{
    return <div>
        <h1> About Page </h1>
        <div>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut faucibus nisi, quis porttitor felis. Vestibulum in ex velit. In vitae orci at lacus scelerisque rhoncus maximus ut lectus. Nulla mattis auctor massa, vel faucibus nibh cursus ut. Vivamus leo sapien, fringilla sed vehicula id, vestibulum vel eros. Nullam sed enim nec neque porttitor facilisis at sed ligula. Nullam dictum consectetur varius. Etiam vitae lobortis lacus. Proin eget arcu velit. Maecenas ultrices, nulla at porta molestie, purus purus lacinia tellus, a efficitur nunc sapien ut enim. Donec vehicula, enim finibus dapibus mattis, tortor lorem porttitor purus, quis viverra odio justo vel turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam sodales bibendum purus at elementum.

Suspendisse potenti. Curabitur et gravida velit. Aliquam vitae vulputate velit. Aliquam erat volutpat. In ut mattis diam, eget vulputate erat. Vivamus dictum nunc justo, non blandit augue malesuada vel. Suspendisse pharetra, tortor quis mollis scelerisque, nunc enim luctus nisl, vel porta dolor eros eget quam. Nulla cursus metus sed orci efficitur, in vulputate augue accumsan. Donec porta, justo vel euismod eleifend, orci felis luctus ipsum, vel tempus lectus nulla sed turpis. Etiam faucibus ac diam sit amet auctor.

Cras nec est et ante pretium ullamcorper. Mauris pellentesque sem elit, quis pretium urna viverra ac. Donec bibendum, purus ac ullamcorper euismod, tellus lorem interdum lacus, eget condimentum metus felis in dui. Suspendisse luctus placerat venenatis. Praesent non dui faucibus, ornare arcu feugiat, aliquet neque. Maecenas purus sem, vehicula sed accumsan ac, dignissim vel neque. Sed imperdiet tortor ut erat tempor, quis auctor ligula tristique. Suspendisse felis orci, dignissim vitae leo sed, tempor cursus mi. Donec suscipit a velit a pretium. Vivamus ultricies dui eget erat posuere, non fringilla dolor rhoncus.

Integer lobortis leo vitae diam hendrerit pretium. Cras a libero vel odio lacinia cursus id eget lacus. Praesent lobortis mollis orci, non maximus lorem tincidunt a. Sed sit amet interdum metus. Praesent lorem quam, congue at purus eget, tempus venenatis enim. Nam est ipsum, laoreet sit amet turpis in, aliquet molestie purus. Maecenas aliquam tempus sem, id hendrerit nunc tempus nec.

Nullam blandit molestie lorem, non accumsan dui molestie vel. Aliquam ornare ante sit amet ultricies sollicitudin. Praesent vel consectetur mi, vitae varius nisl. Sed porta accumsan augue, ut cursus augue lacinia non. Integer placerat mattis turpis at iaculis. Cras pretium lacinia aliquet. Cras ante purus, blandit quis molestie consequat, lacinia in nulla. Maecenas sagittis ut ex eget venenatis. Nulla tristique placerat est id fermentum. Proin eleifend feugiat enim a suscipit. Mauris varius, tortor nec mattis rutrum, neque ex dignissim dui, eu consequat odio augue ac metus. Morbi id bibendum ante. Sed sed justo aliquam, convallis justo sodales, semper turpis. Donec viverra vitae felis nec facilisis. Integer hendrerit nisl nec convallis accumsan.

Sed luctus ante a massa finibus auctor. Ut sagittis magna sapien, at tincidunt elit laoreet sed. Curabitur id sem laoreet, mollis velit et, sodales urna. Ut aliquet ullamcorper felis ut blandit. Aenean finibus ante ultricies dui viverra, ut imperdiet ex sodales. Sed finibus metus ut neque gravida euismod. Vestibulum nec metus sed turpis commodo mollis. Nam posuere dolor tempor turpis egestas rutrum. Donec convallis vehicula lacus sed vestibulum. Fusce non orci nisi. Integer vestibulum mi ut efficitur pellentesque. Donec id eleifend felis.

Nulla tincidunt tristique eros vel porta. Ut scelerisque metus a nisi ultrices, at sodales massa eleifend. In faucibus laoreet velit. Vivamus suscipit dui sed iaculis viverra. Aenean dictum ut ligula ac condimentum. Donec elementum diam vel dui venenatis vulputate. Integer sed interdum sapien. Nullam felis elit, tempus quis commodo ut, mollis sed erat.

Integer orci nunc, ullamcorper at nibh aliquet, iaculis facilisis nisi. In pulvinar tempus congue. Curabitur luctus bibendum blandit. Phasellus pharetra, nulla vel consectetur porttitor, mauris ligula convallis libero, sit amet eleifend ante mauris sit amet est. Sed sit amet turpis elementum, posuere magna ut, hendrerit ligula. Nunc tempor luctus semper. Pellentesque feugiat pellentesque nibh, at viverra orci dignissim quis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc in quam eu ante tincidunt accumsan. Mauris elementum quam ac rhoncus luctus. Quisque condimentum risus enim, id rhoncus mauris porttitor scelerisque. Quisque ac molestie lorem. Vestibulum sollicitudin sagittis lacinia. Proin facilisis magna sit amet lorem vehicula, eu dignissim turpis hendrerit. Sed non ipsum ut nibh facilisis egestas quis sit amet sem.

Duis urna ligula, fringilla ut neque at, varius accumsan leo. Duis dignissim lacus nec rutrum aliquam. Cras nec ex id nibh iaculis tempus a sed tortor. Donec rhoncus purus ut ligula mattis, eget venenatis quam faucibus. Curabitur venenatis, urna congue sollicitudin ultrices, augue magna accumsan nulla, a laoreet sem augue ac tellus. Nulla mollis metus sit amet magna pretium euismod. Donec vel magna dignissim, gravida risus pharetra, ullamcorper leo. Aenean eu magna neque. In volutpat blandit dolor vitae scelerisque. Vivamus et scelerisque arcu, nec semper elit. Aenean accumsan laoreet risus, at ullamcorper mauris scelerisque nec. Vivamus et metus id metus imperdiet pretium vestibulum sit amet diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam vitae leo lobortis, tincidunt tellus a, bibendum quam.

Nunc hendrerit finibus urna a ornare. Curabitur a varius odio. Sed gravida id mi et semper. Donec eros ex, bibendum non dui in, maximus ullamcorper ante. Donec non molestie ante. Proin vel ultricies tellus, sed pretium mauris. Mauris tortor nunc, consectetur et dui id, fermentum sodales sapien. Pellentesque hendrerit sed lectus in rhoncus. Fusce non diam magna. Donec sodales tincidunt diam maximus malesuada. Quisque blandit lacus eget augue lacinia, id placerat dui aliquet. Pellentesque eget nulla consequat, malesuada sapien bibendum, fringilla lorem. Ut eget viverra mi, sit amet volutpat tortor. In sed velit at dui feugiat fringilla.

Cras aliquet commodo sem, id luctus lectus lacinia in. Phasellus tempor eu augue in gravida. Praesent at ornare erat, quis dignissim nibh. Maecenas eget arcu diam. Sed sagittis metus vitae sagittis vestibulum. Suspendisse sit amet tellus tincidunt, lacinia ipsum non, sagittis ante. Duis imperdiet nulla sit amet tempor feugiat. Morbi a laoreet eros. Pellentesque pulvinar risus sed mattis fringilla. Ut.</p></div>
      
    </div>
}

export default About;